### ISSUE TITLE
[KIEKER-744] Add missing entries to libraries-descriptions.txt

### ISSUE THREAD

**Issue by rju** [kieker-monitoring/kieker#1235]
JIRA Issue: [KIEKER-744] Add missing entries to libraries-descriptions.txt
Original Reporter: Andre van Hoorn
 *** 
<p>The file <tt>doc/userguide/libraries-descriptions.txt</tt> is outdate in that it does not contain an entry for each Jar contained in Kieker's <tt>lib/</tt> directory.</p>

<p>Marius: Could you take care of this?</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voorn@pc-vanhoorn:0:~/git_work/kieker/doc/userguide &lt;master&gt; $ grep "jar" libraries-descriptions.txt | awk '{ print $1 }'
derby-$.jar
log4j-$.jar
junit-$.jar
commons-cli-$.jar
commons-logging-$.jar
aspectjweaver-$.jar
aspectjrt-$.jar
aspectjtools-$.jar
aopalliance-$.jar
org.springframework.context-$.jar
org.springframework.web-$.jar
javax.servlet-$.jar
javax.jms-$.jar
cxf-api-$.jar
cxf-rt-bindings-soap-$.jar
sigar-$.jar
jgraphx-$.jar
org.eclipse.emf.common-$.jar
org.eclipse.emf.ecore-$.jar
org.eclipse.emf.ecore.xmi-$.jar
derby-$.jar
</pre>
</div></div>

<p>vs. </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>voorn@pc-vanhoorn:0:~/git_work/kieker/lib &lt;master&gt; $ ls -l *.jar | awk '{ print $9 }'
aopalliance-1.0.jar
aspectjrt-1.7.0.jar
aspectjtools-1.7.0.jar
aspectjweaver-1.7.0.jar
commons-cli-1.2.jar
commons-logging-1.1.1.jar
cxf-api-2.6.2.jar
cxf-rt-bindings-soap-2.6.2.jar
cxf-rt-core-2.6.2.jar
cxf-rt-databinding-jaxb-2.6.2.jar
cxf-rt-frontend-jaxws-2.6.2.jar
cxf-rt-frontend-simple-2.6.2.jar
cxf-rt-transports-http-2.6.2.jar
cxf-rt-transports-http-jetty-2.6.2.jar
derby-10.9.1.0.jar
geronimo-jaxws_2.1_spec-1.0.jar
geronimo-ws-metadata_2.0_spec-1.1.3.jar
javaee-api-5.0.5.jar
javax.jms-1.1.jar
javax.servlet-3.0.jar
jaxb-api-2.0.5.jar
jaxb-impl-2.0.5.jar
jgraphx-1.10.3.1.jar
junit-4.10.jar
log4j-1.2.17.jar
neethi-3.0.2.jar
org.eclipse.emf.common_2.8.0.v20120606-0717.jar
org.eclipse.emf.ecore_2.8.0.v20120606-0717.jar
org.eclipse.emf.ecore.xmi_2.8.0.v20120606-0717.jar
org.springframework.aop-3.1.2.jar
org.springframework.asm-3.1.2.jar
org.springframework.beans-3.1.2.jar
org.springframework.context-3.1.2.jar
org.springframework.core-3.1.2.jar
org.springframework.expression-3.1.2.jar
org.springframework.instrument-3.1.2.jar
org.springframework.web-3.1.2.jar
org.springframework.web.portlet-3.1.2.jar
org.springframework.web.servlet-3.1.2.jar
org.springframework.web.struts-3.1.2.jar
sigar-1.6.4.jar
stax-1.2.0.jar
wsdl4j-1.6.2.jar
xmlschema-core-2.0.2.jar
</pre>
</div></div>

[KIEKER-744]: https://kieker-monitoring.atlassian.net/browse/KIEKER-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by marius** [comment]
wrong marius

**Comment by rju** [comment]
Sorry, we migrated tickets from Jira. And it seems some old tickets contain user names in the descriptions.
